version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: go_db
    volumes:
      - ./.mysql/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    container_name: mysql-container
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    ports:
      - 8081:80
    volumes: 
      - /sessions
  golang:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - ..:/go/src
    ports:
      - 8888:8888
    tty: true
    # links:
      # - mysql